const Message = require('../models/Message');
const Chat = require('../models/Chat');
const User = require('../models/User');
const { getLinkPreview } = require('link-preview-js');

/**
 * Chat-related Socket event handlers
 */
module.exports = (io, socket) => {
  
  // Helper to extract URL from text
  const extractUrl = (text) => {
    const urlRegex = /(https?:\/\/[^\s]+)/g;
    const matches = text.match(urlRegex);
    return matches ? matches[0] : null;
  };

  // Helper to fetch link preview
  const fetchLinkPreviewData = async (url) => {
    try {
      const data = await getLinkPreview(url, {
        timeout: 3000,
        headers: {
          "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
        },
      });
      
      if (data && (data.title || data.description)) {
        return {
          title: data.title,
          description: data.description,
          image: data.images && data.images.length > 0 ? data.images[0] : (data.favicons && data.favicons.length > 0 ? data.favicons[0] : null),
          url: data.url,
          siteName: data.siteName,
        };
      }
      return null;
    } catch (error) {
      console.error('Error fetching link preview:', error.message);
      return null;
    }
  };

  // Join a private chat room
  const joinChat = (room) => {
    socket.join(room);
    console.log(`💬 User joined chat room: ${room}`);
  };

  // Handle new message
  const newMessage = async (newMessageReceived) => {
    const { senderId, content, type, chatId, replyTo } = newMessageReceived;

    if (!senderId || !content || !chatId) {
      return console.log('❌ Invalid message data received');
    }

    try {
      // Fetch the chat to get users
      const chat = await Chat.findById(chatId).populate("users", "_id");
      if (!chat) return console.log('❌ Chat not found');

      // Check for link preview
      let linkPreviewData = null;
      const url = extractUrl(content);
      if (url && (type === 'text' || !type)) {
        linkPreviewData = await fetchLinkPreviewData(url);
      }

      // Save message to database
      const message = await Message.create({
        sender: senderId,
        content: content,
        type: type || 'text',
        status: 'sent',
        chat: chatId,
        replyTo: replyTo || null,
        linkPreview: linkPreviewData,
        // For 1-on-1, receiver is the other user. For group, it can be null.
        receiver: chat.isGroupChat ? null : chat.users.find(u => u._id.toString() !== senderId.toString())?._id,
        readBy: [senderId] // Sender has obviously read their own message
      });

      console.log(`💾 Message saved to DB: ${message._id}`);

      // Update the chat document with the latest message
      await Chat.findByIdAndUpdate(chatId, {
        latestMessage: message._id,
      });
      console.log(`🔄 Chat ${chatId} updated with latest message`);

      // Get sender details to include in the broadcast
      const sender = await User.findById(senderId);
      
      // Populate replyTo if it exists
      let populatedMessage = message;
      if (replyTo) {
        populatedMessage = await Message.findById(message._id).populate({
          path: "replyTo",
          select: "content sender",
          populate: { path: "sender", select: "name" }
        });
      }

      // Broadcast to all users in the chat except the sender
      chat.users.forEach(user => {
        if (user._id.toString() === senderId.toString()) return;

        socket.in(user._id.toString()).emit('message-received', {
          ...newMessageReceived,
          _id: message._id,
          createdAt: message.createdAt,
          senderName: sender?.name,
          senderNumber: sender?.number,
          status: 'sent',
          replyTo: populatedMessage.replyTo,
          linkPreview: linkPreviewData
        });
      });
      
      console.log(`📩 Message relayed to users in chat: ${chatId}`);

      // Notify the sender that the message was successfully saved and send back the populated message
      socket.emit('message-sent', {
        tempId: newMessageReceived.id, // The temporary ID generated by the frontend
        message: {
          ...populatedMessage._doc,
          _id: message._id,
          linkPreview: linkPreviewData
        }
      });
    } catch (error) {
      console.error('❌ Error saving message:', error.message);
    }
  };

  // Handle message reaction
  const addReaction = async ({ messageId, userId, emoji, chatId }) => {
    try {
      const message = await Message.findById(messageId);
      if (!message) return;

      // Check if user already reacted with this emoji
      const existingReactionIndex = message.reactions.findIndex(
        (r) => r.user.toString() === userId.toString() && r.emoji === emoji
      );

      if (existingReactionIndex > -1) {
        // Remove reaction if it already exists (Toggle behavior)
        message.reactions.splice(existingReactionIndex, 1);
      } else {
        // Add new reaction
        message.reactions.push({ user: userId, emoji });
      }

      await message.save();

      // Broadcast to all users in the chat
      const chat = await Chat.findById(chatId).populate("users", "_id");
      chat.users.forEach(user => {
        socket.in(user._id.toString()).emit('message-reacted', {
          messageId,
          reactions: message.reactions,
          chatId
        });
      });

      console.log(`😀 Reaction ${emoji} ${existingReactionIndex > -1 ? 'removed from' : 'added to'} message ${messageId}`);
    } catch (error) {
      console.error('❌ Error in add-reaction:', error.message);
    }
  };

  // Handle message delivered (Receiver got the message)
  const messageDelivered = async ({ messageId, senderId }) => {
    try {
      // ONLY update to delivered if current status is 'sent'
      const message = await Message.findOneAndUpdate(
        { _id: messageId, status: 'sent' },
        { status: 'delivered', deliveredAt: Date.now() },
        { new: true }
      );

      if (message) {
        // Notify the sender that the message was delivered
        socket.in(senderId).emit('message-status-updated', {
          messageId,
          chatId: message.chat,
          status: 'delivered'
        });
        console.log(`✔ Message ${messageId} marked as delivered`);
      }
    } catch (error) {
      console.error('❌ Error in message-delivered:', error.message);
    }
  };

  // Handle message seen (Receiver opened the chat)
  const messageSeen = async ({ chatId, senderId, receiverId }) => {
    try {
      // 1. Add the receiver to the readBy array for all messages they haven't read yet
      await Message.updateMany(
        { chat: chatId, sender: { $ne: receiverId }, readBy: { $ne: receiverId } },
        { $addToSet: { readBy: receiverId } }
      );

      // 2. For 1-on-1 chats, we still update the status to 'seen' for UI ticks
      if (senderId && receiverId) {
        await Message.updateMany(
          { chat: chatId, sender: senderId, receiver: receiverId, status: { $ne: 'seen' } },
          { status: 'seen', seenAt: Date.now() }
        );

        // Notify the sender that their messages were read (to update ticks to blue)
        socket.in(senderId).emit('messages-seen', {
          chatId,
          senderId,
          receiverId
        });
      } else {
        // For group chats, we broadcast to the room that someone read messages
        // (This can be used to update unread counts for that user on other devices)
        socket.to(chatId).emit('messages-seen', {
          chatId,
          receiverId
        });
      }

      // Notify the receiver that they read the messages (to sync unread counts across devices)
      socket.emit('messages-seen', {
        chatId,
        senderId,
        receiverId
      });
      
      console.log(`✔ Messages in chat ${chatId} marked as seen by ${receiverId}`);
    } catch (error) {
      console.error('❌ Error in message-seen:', error.message);
    }
  };

  // Handle typing status
  const typing = ({ chatId, receiverId }) => {
    if (receiverId) {
      socket.in(receiverId).emit('typing', { chatId, userId: socket.id });
    } else {
      socket.to(chatId).emit('typing', { chatId, userId: socket.id });
    }
  };

  const stopTyping = ({ chatId, receiverId }) => {
    if (receiverId) {
      socket.in(receiverId).emit('stop-typing', { chatId, userId: socket.id });
    } else {
      socket.to(chatId).emit('stop-typing', { chatId, userId: socket.id });
    }
  };

  // Register events
  socket.on('join-chat', joinChat);
  socket.on('new-message', newMessage);
  socket.on('add-reaction', addReaction);
  socket.on('message-delivered', messageDelivered);
  socket.on('message-seen', messageSeen);
  socket.on('typing', typing);
  socket.on('stop-typing', stopTyping);
};
